

function Footer() {
  return (
    <div className='h-15 border-t-[1px] flex items-center justify-center'>
        <p className='text-sm py-5'>Generated by Artem<span className='text-blue-600'>Dev</span> for <span className='text-blue-600'>RentalCar</span> </p>
    </div>
  )
}

export default Footer